// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto_Estudo_Das_Interfaces.Data;

namespace Projeto_Estudo_Das_Interfaces.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Projeto_Estudo_Das_Interfaces.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Aluno");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Idade = 30,
                            Nome = "Maria"
                        },
                        new
                        {
                            Id = 2,
                            Idade = 25,
                            Nome = "José"
                        },
                        new
                        {
                            Id = 3,
                            Idade = 28,
                            Nome = "Amanda"
                        },
                        new
                        {
                            Id = 4,
                            Idade = 19,
                            Nome = "Paulo"
                        },
                        new
                        {
                            Id = 5,
                            Idade = 20,
                            Nome = "Fernanda"
                        },
                        new
                        {
                            Id = 6,
                            Idade = 18,
                            Nome = "Camila"
                        },
                        new
                        {
                            Id = 7,
                            Idade = 21,
                            Nome = "Ana"
                        },
                        new
                        {
                            Id = 8,
                            Idade = 23,
                            Nome = "Germano"
                        },
                        new
                        {
                            Id = 9,
                            Idade = 17,
                            Nome = "Selma"
                        },
                        new
                        {
                            Id = 10,
                            Idade = 22,
                            Nome = "Vitor"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
